### ISSUE TITLE
Looks like kanban-fetch is failing on the beta 2.1 builds of OF2

### ISSUE THREAD

**Issue by naupaka** [jyruzicka/kanban-fetch#2]
`$ kanban-fetch -o ~/.kb/out.db`    
`2015-01-15 09:53:28.209 kanban-fetch[39023:4292206] Can't find app with identifier com.omnigroup.OmniFocus2.Today`

Where is the "Today" from?

`$ osascript -e 'id of app "OmniFocus"'`    
`com.omnigroup.OmniFocus2`

**Comment by jyruzicka** [comment]
:frowning: 

Huh, weird. `JROFBridge` gets the id by parsing every running process for its id, and then finding the first one which starts with `com.omnigroup.OmniFocus`. It looks like the beta is spawning another process with OmniFocus2.Today.

Relevant applescript snippet to find running processes from omnigroup:

```
tell application "System Events"
	bundle identifier of (processes where its bundle identifier contains "omnigroup")
end tell
```

**Comment by jyruzicka** [comment]
(Also, when did OmniGroup release an OF beta and not tell me? So rude.)

**Comment by naupaka** [comment]
Now Yosemite-ified: http://update.omnigroup.com/releasenotes/omnifocus-2/OmniFocus-2.1.x-r224198-Test/

**Comment by naupaka** [comment]
Oh! I bet "Today" is from the notification center widget in the OS sidebar! (which was just added in this build). So to fix, update the applescript to find contains "omnigroup" but not "today"

**Comment by jyruzicka** [comment]
Changes made to JROFBridge, and updated on the site as well. Should all work now!
